### ISSUE TITLE
UpdatedAt columns

### ISSUE THREAD

**Issue by affanshahid** [exograph/exograph#1090]
What is the recommended way to add updatedAt columns to postgres entities? Using interceptors somehow?

**Comment by ramnivas** [comment]
Currently, creating a trigger (similar to the one described in https://aviyadav231.medium.com/automatically-updating-a-timestamp-column-in-postgresql-using-triggers-98766e3b47a0) should do the job. An `around` interceptor can also do the job, but it is more work (and will have the limitation of working only through Exograph APIs).

However, we should support this in Exograph proper. Two possibilities:
1. Add the trigger for each field marked with `@updatedAt` during schema creation.
2. Automatically add the field during each update (setting its value to `now()).

The first solution is preferred since it covers updates from non-Exograph systems.

We still need to support `readonly` fields to remove them from mutation APIs. See https://github.com/exograph/exograph/issues/907 and https://github.com/exograph/exograph/issues/926.

(We can also handle `createAt` in the same way)

Let me know your thoughts and fitness for your use case, and we can go from there.

**Comment by affanshahid** [comment]
I think the trigger approach is probably superior and would work for most use cases. One thought around the readonly discussion, I am currently achieving this using:

```
@access(query = true, mutation = false)
createdAt: Instant = now()
```

This causes it to still show up in mutation APIs but gives an authz error if you specify it.

**Comment by ramnivas** [comment]
Thanks for your input.

That is a good workaround for readonly field, indeed!
